#! /bin/bash

HOME="$NOTES/Todo"
TODOS="$HOME/$(date +%Y-%B-%d).md"
INRANGE=0
[[ ! -d "$HOME"  ]] && mkdir -p $HOME

# ------------------------- complete context -------------------------

declare -a COMMANDS=(add all clean done help home list remove undone)

if [[ -n $COMP_LINE ]]; then
    for c in "${COMMANDS[@]}"; do
        [[ ${c:0:${#2}} == "${2,,}" ]] && echo "$c"
    done
    exit
fi

_help() {
    echo "Simple terminal todo"
    echo "Usage: todo [OPTIONS] [COMMAND] [TASK]"
    echo
    echo "Commands:"
    echo "  add		add new task"
    echo "  remove	remove a task"
    echo "  done		mark task as done by getting task number"
    echo "  undone	mark task as undone by getting task number"
    echo "  list		list of today's tasks"
    echo "  all		list of all undone tasks from all days"
    echo "  home		returns todo's home"
    echo "  clean		clean empty todo files"
    echo "  help  	show this message"
    echo
    echo "Options:"
    echo "  -r    	run command on range. example: todo -r remove 1-3"
    echo "  -h    	show this message"
}

while getopts "rh?" opt 
do
   case "$opt" in
      r)
        INRANGE=1 ;;
      h\?) # display _help
         _help
         exit;;
   esac
done

shift $((OPTIND-1))
[ "${1:-}" = "--" ] && shift

case $1 in
  "all") 
    for file in $HOME/*
    do 
      if [[ -s "$file" ]]; then
        if [[ $(grep -c '\- \[ \]' $file) -gt 0 ]]; then
          basename -- $file | cut -d. -f1  
          grep '\- \[ \]' $file
          echo 
        fi
      fi
    done 
    ;;
  "add") 
    [[ ! -f "$TODOS" ]] && touch $TODOS
    echo -e "- [ ] ${@: 2}" >> $TODOS 
    ;;
  "remove") 
    [[ ! -f "$TODOS" ]] && echo "There is no todo file." && exit 1
    if [[ $INRANGE -eq 1 ]]; then
      START=$(echo $2 | cut -d "-" -f1)
      END=$(echo $2 | cut -d "-" -f2)
      sed -i "${START},${END}d" $TODOS 
      exit 0
    fi
    LINES="${@: 2}"
    for LINE in $LINES; do
      sed -i "${LINE}d" $TODOS 
    done  
    ;;
  "list") 
    [[ ! -f "$TODOS" ]] && echo "There is no todo file to list." && exit 1
    if [[ -s "$TODOS" ]]; then
      date +%Y-%B-%d
      cat -n $TODOS
    else
      echo "There is no todo to show!"
    fi
    ;;
  "done") 
    if [[ $INRANGE -eq 1 ]]; then
      START=$(echo $2 | cut -d "-" -f1)
      END=$(echo $2 | cut -d "-" -f2)
      sed -i "${START},${END}s/- \[ \]/- \[x\]/" $TODOS
      exit 0
    fi
    LINES="${@: 2}"
    for LINE in $LINES; do
      sed -i "${LINE}s/- \[ \]/- \[x\]/" $TODOS
    done  
    ;;
  "undone") 
    if [[ $INRANGE -eq 1 ]]; then
      START=$(echo $2 | cut -d "-" -f1)
      END=$(echo $2 | cut -d "-" -f2)
      sed -i "${START},${END}s/- \[x\]/- \[ \]/" $TODOS
      exit 0
    fi
    LINES="${@: 2}"
    for LINE in $LINES; do
      sed -i "${LINE}s/- \[x\]/- \[ \]/" $TODOS
    done  
    ;;
  "clean") find $HOME -type f -empty -delete ;; 
  "home") 
    echo $HOME
    exit 0
    ;;
  *) _help ;;
esac
